In [2]:
import numpy as np
import pandas as pd

# Debugging

In [2]:
from IPython.core.debugger import set_trace

def add_to_life_universe_everything(x):
    answer = 42
    set_trace()
    answer += x
    
    return answer

add_to_life_universe_everything(12)

> <ipython-input-2-08b95681be7a>(6)add_to_life_universe_everything()
      4     answer = 42
      5     set_trace()
----> 6     answer += x
      7 
      8     return answer



ipdb>  answer


42


ipdb>  n


> <ipython-input-2-08b95681be7a>(8)add_to_life_universe_everything()
      6     answer += x
      7 
----> 8     return answer
      9 
     10 add_to_life_universe_everything(12)



ipdb>  q


BdbQuit: 

In [2]:
from pdb import set_trace

def add_to_life_universe_everything(x):
    answer = 42
    set_trace()
    answer += x
    
    return answer

add_to_life_universe_everything(12)

> <ipython-input-2-d091819fce65>(6)add_to_life_universe_everything()
-> answer += x


(Pdb)  n


> <ipython-input-2-d091819fce65>(8)add_to_life_universe_everything()
-> return answer


(Pdb)  q


BdbQuit: 

# Formatting

In [1]:
import math

def format_large(x):
    order = math.ceil(math.log(x, 10))
    x_str = '%.f' % x
    ret = x_str[order-3:order]
    for i in range(1, math.ceil(math.ceil(order)/3)-1):
        ret = x_str[order-3*(i+1):order-3*i] + ',' + ret
    ret = x_str[0:order-3*(i+1)] + ',' + ret
    return ret
    
format_large(1234567890.123)

'1,234,567,890'

# General

## Variables

In [19]:
a = b = c = 0
b = 1
a

0

In [22]:
a = b = None
b = 1
print(a)


None


## Funktionen

In [1]:
a = 1
def fkt(a=a):
    a=2
fkt()
print(a)

1


In [2]:
a = 1
def fkt(a=a):
    b = a
    global a
    a = b
fkt()
print(a)

SyntaxError: name 'a' is parameter and global (<ipython-input-2-5057881cfc34>, line 7)

### *args for variable number of arguments

In [1]:
def fkt(*args): # pack to tuple
    print(type(args)) # tuple
    print(*args) # unpack
    print(*list(args)) # to list, then unpack
    print('%s' % list(args)) 
    
fkt(1,2,3)
fkt()

<class 'tuple'>
1 2 3
1 2 3
[1, 2, 3]
<class 'tuple'>


[]


### *kargs for variable number of keyword arguments 

In [2]:
def fkt(**kwargs):  
    for key, value in kwargs.items(): 
        print("%s == %s" % (key, value)) 
  

fkt(first ='1', second ='2')  

first == 1
second == 2


### Using *args and **kwargs to call a function

In [5]:
def fkt(arg1, arg2): 
    print("arg1:", arg1) 
    print("arg2:", arg2) 

args = ("1", "2") 
fkt(*args) 

kwargs = {"arg1" : "1", "arg2" : "2"} 
fkt(**kwargs) 


arg1: 1
arg2: 2
arg1: 1
arg2: 2


### *args and **kwargs

In [ ]:
def fkt(*args,**kwargs): 
	print("args: ", args) 
	print("kwargs: ", kwargs) 


# Now we can use both *args ,**kwargs 
# to pass arguments to this function : 
myFun('geeks','for','geeks',first="Geeks",mid="for",last="Geeks") 


### Returning tuples

In [42]:
def fkt(a):
    if a == 1:
        return 1, 2
    return 1

c, d = fkt(1)
print(c, d)
c, *d = fkt(0)

1 2


TypeError: cannot unpack non-iterable int object

In [1]:
def square(x):
    return x*xs

b = square
print(b(2))

4


### Synchronized function

In [14]:
import threading
import time
from datetime import datetime


lock = threading.Lock()

def synchronized():
    lock.acquire()
    time.sleep(3) # 10 secs
    print(datetime.now().time())
    lock.release()
    

t1 = threading.Thread(target=synchronized)  
t2 = threading.Thread(target=synchronized)  

t1.start()
t2.start()
    


15:00:16.271423
15:00:19.281131


## Nested functions

In [47]:
def outer():
    
    def inner():
        return 1
    
    print(inner())
    
outer()

1


## Math

In [5]:
import math

### Rounding, etc.

In [12]:
print(round(.5))
print(round(0.55, 1))
print(math.floor(.5))
print(math.floor(.55 * 10) / 10)
print(math.ceil(.4))

0
0.6
0
0.5
1


## Vectors

In [43]:
import numpy as np

### Comparisons

In [49]:
u = np.array([1,2,3])
v = np.array([1,2,3])
w = np.array([1,1,1])
O = np.array([0,0,0])
print((u == v).all())
print((u == w).all())
print((u == w).any())
print((u == O).any())

True
False
True
False


In [9]:
a = np.array([1,1])
b = np.array([2,2])
c = np.array([3,3])
# (a < b < c).all() => Value error
(a < b).all() and (b < c).all()
((a < b) & (b < c)).all()

True

In [16]:
a = np.array([1,2,1,2]).reshape(2,2)
b = np.array([1,2,1,2]).reshape(2,2)
print(a)
a == b

[[1 2]
 [1 2]]


array([[ True,  True],
       [ True,  True]])

In [16]:
a = np.array([1,2,1,2]).reshape(2,2)
b = np.array([1,2,1,2]).reshape(2,2)
print(a)
a == b

[[1 2]
 [1 2]]


array([[ True,  True],
       [ True,  True]])

Compare each row of a with b

In [24]:
a = np.array([1,2,1,2]).reshape(2,2)
print(a)
b = np.array([1,2])
print(b)
a == b

[[1 2]
 [1 2]]
[1 2]


array([[ True,  True],
       [ True,  True]])

Compare each col of a with b

In [44]:
a = np.array([1,2,3,4,5,6]).reshape(2,3)
print(a)
column = np.array([2,5])
print(column)
print(np.repeat(column, a.shape[1]))
mat = np.repeat(column, a.shape[1]).reshape(a.shape)
print(mat)
a == b

[[1 2 3]
 [4 5 6]]
[2 5]
[2 2 2 5 5 5]
[[2 2 2]
 [5 5 5]]


array([[False,  True, False],
       [False,  True, False]])

### Column and row sums

In [22]:
a = np.array([1,2,3,4]).reshape(2,2)
print(a)
print(a.sum())
print(a.sum(0)) # col
print(a.sum(1)) # row

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


### Mappings

In [55]:
from functools import reduce
d = {'v': np.array([2,3,4]), 'w': np.array([4,3,2])}
print(d)
x = reduce(lambda x,y: x+y, d.values(), np.zeros(list(d.values())[0].shape[0]))
print(x)

{'v': array([2, 3, 4]), 'w': array([4, 3, 2])}
[6. 6. 6.]


## Map list to single value

In [2]:
from functools import reduce

numbers = [1,2,3,4,5]
print('Sum of %s is %d' % (numbers, numbers[len(numbers)-1] * (numbers[len(numbers)-1]+1) / 2))
print(reduce(lambda x, y: x + y, numbers, 0))

numbers = []
print(reduce(lambda x, y: x + y, numbers, 0))

class A:
    def __init__(self):
        self.a = 1
        
lst = [A(), A(), A()]
print(reduce(lambda x,y: x+y.a, lst, 0))

Sum of [1, 2, 3, 4, 5] is 15
15
0
3


Sum of tuple differences

In [3]:

l1 = [1,2,3]
l2 = [4,5,6]
reduce(lambda x,y: x+y[1]-y[0], zip(l1,l2), 0)

9

## Copy

In [18]:
d = {1:2, 3:4}
print(d)
c = d.copy()
c[5] = 6
print(c)
print(d)

{1: 2, 3: 4}
{1: 2, 3: 4, 5: 6}
{1: 2, 3: 4}


In [20]:
d = {'a': [1, 2, 3], 'b': [4, 5, 6]}
c = d.copy()
c['c'] = 'new'
print(d)

{'a': [1, 2, 3], 'b': [4, 5, 6]}


In [24]:
d = {'a': {1: [1, 2], 2: [4,5]}}
c = d['a'].copy()
c[1].pop(0)
print(d)

# ==> deep copy

import copy
d = {'a': {1: [1, 2], 2: [4,5]}}
c = copy.deepcopy(d['a'])
c[1].pop(0)
print(d)

{'a': {1: [2], 2: [4, 5]}}
{'a': {1: [1, 2], 2: [4, 5]}}


# OOP

### Static

In [8]:
class A:
    
    static_field = "a"
    
    @classmethod
    def static_fkt(cls):
        print(cls.static_field)
        cls.static_field += "a"
        print(cls.static_field)

A.static_fkt()

a
aa


### Factory method

Mehr hier: https://iscinumpy.gitlab.io/post/factory-classmethods-in-python/

In [11]:
class A(object):  # inherits from object

    @classmethod
    def get_new_inst(cls, x):
        return cls(x)

    def __init__(self, x):
        self.x = x

    def __str__(self):
        return 'A[x=%s]' % self.x
    
print(A.get_new_inst(1))


A[x=1]


### Inheritance

In [21]:
class A:
    
    def __init__(self, a):
        self.a = a
    
    def say_hi(self):
        print('hi')

class B(A):
    
    def __init__(self, a, b):
        super().__init__(a)
        self.b = b

    def call_super_method(self):
        super().say_hi()
        self.say_hi()
        
    def set_super_attr(self):
        self.a = 3
        # NOT: super().a = 3
    
    def __str__(self):
        return 'B [%s, %s]' % (self.a, self.b)
    

b = B(1, 2)
print(b)
b.call_super_method()
b.set_super_attr()
print(b)

B [1, 2]
hi
hi
B [3, 2]


In [13]:
if hasattr(b, 'a'):
    print('b has the property a, value = %s' % b.a)

b has the property a, value = 1


In [16]:
if isinstance(b, A):
    print('b is an A')

a = A(3)
if not isinstance(a, B):
    print('a is not a B')


b is an A
a is not a B


In [4]:
class A:
    def __init__(self):
        self.lst = [1,2,3,4]
    
    def __iter__(self):
        return iter(self.lst)

a = A()
for i in a:
    print(i) 


1
2
3
4


# Data structures

## Lists

In [33]:
lst = [5, 4, 1, 7]
lst.sort()
print(lst)

[1, 4, 5, 7]


In [34]:
lst = [(5,1), (4,7), (1,2), (7,3)]
lst.sort(key=lambda x: x[1], reverse=True)
print(lst)

[(4, 7), (7, 3), (1, 2), (5, 1)]


## Maps


In [23]:
d = {'a': 1, 'b': 2, 'c': 3}
print(d)

print(d.values(), type(d.values()))
print(sum(d.values()))
print(max(d.values()))

{'a': 1, 'b': 2, 'c': 3}
dict_values([1, 2, 3]) <class 'dict_values'>
6
3


In [30]:
d = {1: 2, 3: 4}
d.update({'a': 5, 'b': 6})
print(d)

{1: 2, 3: 4, 'a': 5, 'b': 6}


In [6]:
d.update((k,v+1) for k,v in d.items() if v%2 == 0)
print(d)

d2 = dict(filter(lambda i: i[1] > 1, d.items()))
print(d2)

d2 = {k:v for (k,v) in d.items() if v > 1}
print(d2)

{'a': 1, 'b': 2, 'c': 3}
{'a': 1, 'b': 3, 'c': 3}
{'b': 3, 'c': 3}
{'b': 3, 'c': 3}


## Queues

In [5]:
from queue import Queue
from queue import PriorityQueue

q = PriorityQueue()
q.put(3)
q.put(2)
q.put(4)
q.put(1)
while q.qsize() > 0:
    print(q.get())

1
2
3
4


# Random

In [ ]:
from datetime import datetime, timedelta
import numpy as np

def random_date(start, end, n=1):
    """ Generate a random datetime between start and end (exclusive) """
    start = datetime.strptime(start,'%Y-%m-%d')
    end = datetime.strptime(end,'%Y-%m-%d')
    if n == 1:
        return start + timedelta(days=np.random.randint(0, int((end - start).days)))
    return [start + timedelta(days=np.random.randint(0, int((end - start).days))) for i in range(n)]

random_date('2019-01-01', '2019-01-03', n=2)

# Data

In [6]:
df = pd.DataFrame({'col 1': [1,3,4,5,6,7,8], 
                   'col 2': [4,5,6,7,8,9,0]})
df.head()

col 1  col 2
0      1      4
1      3      5
2      4      6
3      5      7
4      6      8

In [10]:
df = pd.DataFrame({'col 1': np.array([1,3,4,5,6,7,8]), 
                   'col 2': np.array([4,5,6,7,8,9,0])})
df.head()

col 1  col 2
0      1      4
1      3      5
2      4      6
3      5      7
4      6      8

In [11]:
# Column by position
df.iloc[:,0]

0    1
1    3
2    4
3    5
4    6
5    7
6    8
Name: col 1, dtype: int64

In [14]:
df = pd.DataFrame({'Year': [21,21,19,19,20,20],'Month': [6,1,6,1,6,1]})
df.sort_values(['Year', 'Month'], inplace=True)
df.head(10)

Year  Month
3    19      1
2    19      6
5    20      1
4    20      6
1    21      1
0    21      6

## Conditions & filter

In [16]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'Day': [1,2,3,4,5]*2,'Key': [1,1,1,1,np.nan,2,2,2,2,np.nan]})
df.head(10)

Day  Key
0    1  1.0
1    2  1.0
2    3  1.0
3    4  1.0
4    5  NaN
5    1  2.0
6    2  2.0
7    3  2.0
8    4  2.0
9    5  NaN

Filter out some days for the key 2

In [17]:
df[(df['Key'] != 2) | (~df['Day'].isin([1,2,3]))]

Day  Key
0    1  1.0
1    2  1.0
2    3  1.0
3    4  1.0
4    5  NaN
8    4  2.0
9    5  NaN

Drop NaN's

In [20]:
df.dropna()

Day  Key
0    1  1.0
1    2  1.0
2    3  1.0
3    4  1.0
5    1  2.0
6    2  2.0
7    3  2.0
8    4  2.0

In [22]:
df[df.Key != 1.0]

Day  Key
4    5  NaN
5    1  2.0
6    2  2.0
7    3  2.0
8    4  2.0
9    5  NaN

## Write to Excel

### openpyxl

Does strange changes to the file. 

In [3]:
import pandas as pd
import os.path
from openpyxl import load_workbook


def create_or_append_to_excel_sheet(df, path, sheet_name):
    if not os.path.isfile(path):
        print('create new file')
        df.to_excel(path, sheet_name=sheet_name, startrow=0, index=False)
        return 
    print('append to existing file')
    # TODO: check if sheet exists
    existing_data = pd.read_excel(path, sheet_name=sheet_name)
    last_row_num = existing_data.iloc[:,0].shape[0]
    writer = pd.ExcelWriter(path, engine='openpyxl') 
    book = load_workbook(path)
    writer.book = book
    writer.sheets = dict((ws.title, ws) for ws in book.worksheets)
    df.to_excel(writer, sheet_name, header=False, startrow=last_row_num + 1, index=False)
    writer.save()
    writer.close()

    
df = pd.DataFrame({'a':[1,2,3,4], 'b':[4,5,6,7]})
path = './test.xlsx'
sheet_name = 'Sheet 1'

create_or_append_to_excel_sheet(df, path, sheet_name)

append to existing file


In [4]:
pwd

'C:\\Users\\49856\\Dropbox\\workspace_spyder'

This somehow corrupts the excel file, so that next time when reading data from it with pandas, it tries to read formulas instead of values, which become Nan-s.

# Dates

In [7]:
from datetime import datetime, time, timedelta

dt = datetime.strptime('2010-10-01 12:12', '%Y-%m-%d %H:%M')
datetime.strftime(dt, '%Y-%m-%d %H:%M')

'2010-10-01 12:12'

In [8]:
import humanize

delta = timedelta(hours=-500)
print(str(delta))
print(humanize.naturaltime(delta))


-21 days, 4:00:00
20 days from now


In [17]:
import math

a = 2.5
time_ = time(hour=math.floor(a), minute=round((a-math.floor(a))*60))
print(time_)

02:30:00


In [20]:
import pandas as pd

t = pd.Timestamp('2013-12-25 00:01:01')
print(t, type(t))

d = t.date() 
print(d, type(d))
dt = t.to_pydatetime()
print(dt, type(dt))

2013-12-25 00:01:01 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
2013-12-25 <class 'datetime.date'>
2013-12-25 00:01:01 <class 'datetime.datetime'>


# Profiling

In [3]:
import gc
import sys
import _pickle as cPickle

def memory_dump():
    with open("memory.pickle", 'wb') as dump:
        xs = []
        for obj in gc.get_objects():
            i = id(obj)
            size = sys.getsizeof(obj, 0)
            #    referrers = [id(o) for o in gc.get_referrers(obj) if hasattr(o, '__class__')]
            referents = [id(o) for o in gc.get_referents(obj) if hasattr(o, '__class__')]
            if hasattr(obj, '__class__'):
                cls = str(obj.__class__)
                xs.append({'id': i, 'class': cls, 'size': size, 'referents': referents})
        cPickle.dump(xs, dump)
        
memory_dump()

In [8]:
with open("memory.pickle", 'rb') as dump:
    objs = cPickle.load(dump)
for i in objs[0:10]:
    print(i)

{'id': 2449151045864, 'class': "<class 'tuple'>", 'size': 80, 'referents': [2449140336944, 2449140284336, 2449098058544, 2449097815984]}
{'id': 2449228826824, 'class': "<class 'list'>", 'size': 64, 'referents': []}
{'id': 2449205008712, 'class': "<class 'tuple'>", 'size': 56, 'referents': [2449175658992]}
{'id': 2449175666504, 'class': "<class 'ValueError'>", 'size': 88, 'referents': [2449205008712, 2449135863048, 2449175641544]}
{'id': 2449173767112, 'class': "<class 'traceback'>", 'size': 64, 'referents': [2449166872280]}
{'id': 2449166872280, 'class': "<class 'frame'>", 'size': 432, 'referents': [2449166305400, 2449132012432, 2449097942424, 2449131963240, 2449130528872, 2449128501800]}
{'id': 2449128677128, 'class': "<class 'traceback'>", 'size': 64, 'referents': [2449173767112, 2449166305400]}
{'id': 2449221574216, 'class': "<class 'tuple'>", 'size': 56, 'referents': [2449175659104]}
{'id': 2449175641544, 'class': "<class 'ValueError'>", 'size': 88, 'referents': [2449221574216]}
{'